In [116]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.neighbors import KNeighborsClassifier
import warnings
warnings.filterwarnings("ignore")

In [117]:
df = pd.read_csv('WineQT.csv')
df.head()

   fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  Id
0            7.4              0.70         0.00  ...      9.4        5   0
1            7.8              0.88         0.00  ...      9.8        5   1
2            7.8              0.76         0.04  ...      9.8        5   2
3           11.2              0.28         0.56  ...      9.8        6   3
4            7.4              0.70         0.00  ...      9.4        5   4

[5 rows x 13 columns]

In [118]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [119]:
df.duplicated().sum()

np.int64(0)

In [120]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
 12  Id                    1143 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 116.2 KB

In [121]:
df.describe()

       fixed acidity  volatile acidity  ...      quality           Id
count    1143.000000       1143.000000  ...  1143.000000  1143.000000
mean        8.311111          0.531339  ...     5.657043   804.969379
std         1.747595          0.179633  ...     0.805824   463.997116
min         4.600000          0.120000  ...     3.000000     0.000000
25%         7.100000          0.392500  ...     5.000000   411.000000
50%         7.900000          0.520000  ...     6.000000   794.000000
75%         9.100000          0.640000  ...     6.000000  1209.500000
max        15.900000          1.580000  ...     8.000000  1597.000000

[8 rows x 13 columns]

In [122]:
df = df.drop(['Id'],axis =1)
df.head()

   fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [123]:
x = df.drop(['quality'], axis = 1)
y = df['quality']

# standardizing data

In [124]:
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [125]:
x

array([[-0.52157961,  0.93933222, -1.36502663, ...,  1.27069495,
        -0.57365783, -0.96338181],
       [-0.29259344,  1.94181282, -1.36502663, ..., -0.70892755,
         0.1308811 , -0.59360107],
       [-0.29259344,  1.27349242, -1.16156762, ..., -0.32577481,
        -0.04525363, -0.59360107],
       ...,
       [-1.20853813,  0.38239855, -0.9581086 , ...,  0.88754221,
        -0.45623467,  0.05351522],
       [-1.38027776,  0.10393172, -0.8563791 , ...,  1.33455374,
         0.60057372,  0.70063152],
       [-1.38027776,  0.6330187 , -0.75464959, ...,  1.65384769,
         0.30701583, -0.22382033]], shape=(1143, 11))

In [126]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size= 0.2, random_state=24)

In [127]:
model = KNeighborsClassifier()

In [128]:
params = {'n_neighbors': [1,3,5,7,9,11,13,15,17,19,21,23,25],}

In [129]:
grid = GridSearchCV(model, params, cv = 5)
grid.fit(x_train,y_train)
print('grid best parameters:', grid.best_params_)

grid best parameters: {'n_neighbors': 11}

In [130]:
random = RandomizedSearchCV(model,params, cv= 5)
random.fit(x_train,y_train)
print('random best parameters;', random.best_params_)

random best parameters; {'n_neighbors': 11}

In [131]:
model2 = KNeighborsClassifier(n_neighbors=11)
model2.fit(x_train,y_train)
y_pred = model2.predict(x_test)

In [132]:
y_pred

array([5, 6, 7, 6, 5, 5, 7, 6, 6, 6, 5, 6, 6, 5, 6, 5, 5, 5, 6, 6, 6, 6,
       6, 7, 5, 6, 5, 5, 5, 6, 6, 6, 5, 7, 5, 5, 6, 6, 5, 7, 5, 5, 6, 5,
       6, 6, 6, 6, 6, 5, 6, 5, 6, 6, 7, 6, 5, 5, 6, 5, 5, 5, 5, 6, 6, 5,
       5, 5, 6, 5, 6, 5, 6, 6, 5, 6, 7, 6, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5,
       7, 5, 5, 6, 5, 5, 6, 7, 5, 6, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 5, 6,
       6, 7, 5, 6, 6, 6, 6, 5, 5, 5, 5, 6, 5, 5, 5, 6, 5, 5, 6, 6, 6, 6,
       6, 5, 5, 6, 6, 6, 6, 5, 6, 5, 6, 5, 5, 6, 6, 5, 7, 5, 5, 6, 6, 5,
       6, 5, 6, 6, 5, 5, 6, 5, 5, 6, 6, 7, 6, 5, 5, 5, 5, 5, 5, 6, 6, 6,
       5, 6, 6, 5, 5, 5, 7, 6, 5, 6, 7, 5, 5, 6, 6, 5, 6, 6, 6, 5, 5, 6,
       5, 5, 6, 7, 6, 6, 6, 6, 6, 5, 5, 6, 5, 5, 6, 6, 6, 5, 5, 6, 5, 6,
       5, 7, 5, 5, 5, 6, 7, 7, 6])

In [133]:
print('accuracy score:', accuracy_score(y_test,y_pred))

accuracy score: 0.5240174672489083